# data csv
# defautl profile
# paper size
# records dir

# Base dir is MiniTCM

# The default profile to use.
profile = "profiles/Profile 1.toml"
store = "data/sample_meds_2020-05-26.csv"

# open_after_save = true
# pdfviewer = false

